### PR TITLE
Forward `verbose` keyword argument to HTTP

### LINKED ISSUE #133: Feature request: support (and forward) the `verbose` keyword argument in HTTP.jl
> Possibly, an improvement in FHIRClient could be to support the `verbosity` keyword argument in HTTP.jl and forward it to `HTTP.request` for adjusting the verbosity of the logging messages from HTTP: https://juliaweb.github.io/HTTP.jl/stable/reference/#HTTP.request

_Originally posted by @devmotion in https://github.com/JuliaHealth/FHIRClient.jl/issues/130#issuecomment-1817095896_

### PR DESCRIPTION
**Pull request by devmotion**
The PR adds a `verbose::Int = 0` keyword argument to `FHIRClient.request`, `FHIRClient.request_json` and `FHIRClient.request_raw` that is forwarded to `HTTP.request` and can be used to adjust the verbosity of the logging of the request and response processes.

Fixes #133.

The PR is based on #131.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
It occurs to me that, in the future, there might be other packages that also have verbosity settings that we want to forward.

With that in mind, should we rename our kwarg to something like `verbosity_http` or `verbose_http`, just to distinguish it from other possible verbosity options?

**Comment by DilumAluthge** [comment]
@devmotion Can you rebase this PR on the latest master?

**Comment by devmotion** [comment]
> It occurs to me that, in the future, there might be other packages that also have verbosity settings that we want to forward.
> 
> With that in mind, should we rename our kwarg to something like `verbosity_http` or `verbose_http`, just to distinguish it from other possible verbosity options?

IMO currently it is fine to just use `verbose` since as far as I know HTTP is the only of our dependencies that supports such a verbosity setting in a function we call. I think we should only try to distinguish the HTTP verbosity option from other verbosity options if there are actually other options.

**Comment by DilumAluthge** [comment]
As I see it, we have two options:

1. We keep the name `verbose` for now. In the future, if we add another dependency to FHIRClient where a verbosity kwarg would be useful, we have to rename the existing `verbose` kwarg to `verbose_http`, which would be a breaking change to the public API, and thus we have to bump the major version number of FHIRClient.jl.
2. We change the name to `verbose_http` now. In the future, if we add another dependency to FHIRClient where a verbosity kwarg would be useful, we don't have to rename the existing `verbose_http` kwarg, and thus we don't need to make a breaking release of FHIRClient.jl.

I think that both options are fine. I don't feel particularly strongly one way or another.

@devmotion Which option do you prefer?

**Comment by DilumAluthge** [comment]
@devmotion Can you fix the merge conflicts and rebase on the latest master?

**Comment by devmotion** [comment]
> we have to rename the existing verbose kwarg to verbose_http, which would be a breaking change to the public API, and thus we have to bump the major version number of FHIRClient.jl.

I assumed we might want to keep the `verbose` keyword argument as a "global" setting, regardless of whether additional dependencies are adding support for it or not. I imagined that `verbose_http` etc. could be useful to set verbosity for each dependency separately but `verbose` could be a convenient way to specify a (somewhat) consistent verbosity level for all dependencies that support it. I assume that such an approach would allow us to introduce `verbose_http` etc. in a non-breaking release.

**Comment by DilumAluthge** [comment]
Hmmm. I'm not sure how it would work to have a single global `verbose` for multiple packages.

For example, HTTP.jl uses integers, but another package could use a different type (e.g. enum, symbol, string, or some custom type) for their verbosity option.

Also, even if both HTTP.jl and some other package both use integers for their verbosity kwarg, the values don't necessarily match up. E.g. for HTTP.jl the possible values are 0, 1, 2, 3. But another package could just have 0 or 1. So if the user sets our global kwarg to `verbose = 1`, then for HTTP.jl this means "some verbosity, but not the max", but for the other package this could mean "max verbosity".

So it's not clear to me that we could just forward the same kwarg to multiple packages.

**Comment by devmotion** [comment]
Yes, I assumed that different packages might specify verbosity levels in different ways. Generally, the `verbose` keyword argument would not just be forwarded but mapped to the corresponding settings of the different dependencies (at least for HTTP.jl it would be passed through though). My feeling is still though that currently this seems to be a quite hypothetical scenario since FHIRClient only has very few non-stdlib dependencies (HTTP, JSON3, SaferIntegers, and StructTypes it seems) and the verbosity settings seem to be very HTTP-specific and not widely used (and also not in line with the general Julia logging systems, e.g., IIRC in the discussions in LoggingExtras about such a setup Fredrik seemed to prefer to just use log-levels between -1 and -1000 for debug logging).

**Review by DilumAluthge — APPROVED** [review]

**Review by DilumAluthge — APPROVED** [review]

**Pull request merged**
